### ISSUE TITLE
Error on colcon build at ubuntu 22.04 and ROS2 humble desktop 

### ISSUE THREAD

**Issue by zozolpl** [Myzhar/ldrobot-lidar-ros2#17]
**Describe the bug**
Installed ROS2 following 
https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html
(Desktop install)

Then following https://github.com/Myzhar/ldrobot-lidar-ros2#install-the-node

Getting error on command 
`colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release`
```

root@ROS:/opt/ros/humble# colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release
Starting >>> ament_package
Starting >>> ament_lint                       
Starting >>> gtest_vendor
Starting >>> gtest                                                                
[7.607s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'ament_package' doesn't explicitly install a marker in the package index (colcon-ros currently does it implicitly but that fallback will be removed in the future)
[7.608s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'ament_package' doesn't explicitly install the 'package.xml' file (colcon-ros currently does it implicitly but that fallback will be removed in the future)
[7.650s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'ament_lint' doesn't explicitly install a marker in the package index (colcon-ros currently does it implicitly but that fallback will be removed in the future)
[7.651s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'ament_lint' doesn't explicitly install the 'package.xml' file (colcon-ros currently does it implicitly but that fallback will be removed in the future)
--- stderr: gtest_vendor
CMake Error: The source directory "/opt/ros/humble/share/gtest_vendor" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/cmake/build.py", line 34, in build
    rc = await extension.build(
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 87, in build
    rc = await self._reconfigure(args, env)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/build.py", line 182, in _reconfigure
    buildfile = get_buildfile(cmake_cache)
  File "/usr/lib/python3/dist-packages/colcon_cmake/task/cmake/__init__.py", line 114, in get_buildfile
    if 'Visual Studio' in generator:
TypeError: argument of type 'NoneType' is not iterable
---
Failed   <<< gtest_vendor [0.21s, exited with code 1]
Aborted  <<< ament_package [0.34s]
Aborted  <<< ament_lint [0.28s]
Aborted  <<< gtest [0.25s]                             

Summary: 0 packages finished [7.17s]
  1 package failed: gtest_vendor
  3 packages aborted: ament_lint ament_package gtest
  1 package had stderr output: gtest_vendor
  277 packages not processed
argument of type 'NoneType' is not iterable
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - ROS2 version: Humble desktop
 - Device type: VirtualBox

**Comment by Myzhar** [comment]
Did you clone the node with the option `--recurse-submodules`?
